export const labels = new Map(
  Object.entries({
    signin: {en: 'Sign in', ar: 'تسجيل الدخول'},
    signin_subtitle: {
      en: 'Sign in on the internal platform',
      ar: 'قم بتسجيل الدخول على المنصة الداخلية',
    },
    username: {en: 'User Name', ar: 'اسم المستخدم'},
    password: {en: 'Password', ar: 'كلمه السر'},
    confirm_password: {en: 'Confirm Pasword', ar: 'تأكيد كلمة المرور'},
    signinnow: {en: 'Sign In Now', ar: 'قم بتسجيل دخولك الآن'},
    username_isrequired: {en: 'Username is required', ar: 'اسم المستخدم مطلوب'},
    password_isrequired: {en: 'Password is required', ar: 'كلمة المرور مطلوبة'},
    incorrect_signin: {
      en: 'Incorrect username or password',
      ar: 'اسم المستخدم أو كلمة المرور غير صحيحة',
    },
    pages: {en: 'Pages', ar: 'الصفحات'},
    management: {en: 'Management', ar: 'إدارة'},
    users: {en: 'Users', ar: 'المستخدمين'},
    dashboard: {en: 'Dashboard', ar: 'لوحة القيادة'},
    surveys: {en: 'Surveys', ar: 'الدراسات الاستقصائية'},
    reports: {en: 'Reports', ar: 'تقرير'},
    default: {en: 'Default', ar: 'إفتراضي'},
    analytics: {en: 'Analytics', ar: 'تحليلات'},
    profile: {en: 'Profile', ar: 'الملف الشخصي'},
    general: {en: 'General', ar: 'شامل'},
    security: {en: 'Security', ar: 'أمن'},
    totalcompleted: {en: 'Total Completed', ar: 'إجمالي المنجز'},
    totalviewed: {en: 'Total Viewed', ar: 'مجموع المشاهدة'},
    totalnotviewed: {en: 'Total Not Viewed', ar: 'إجمالي لم يتم مشاهدته'},
    role: {en: 'Role', ar: 'وظيفة'},
    ROLE_ADMIN: {en: 'Admin', ar: 'مشرف'},
    ROLE_USER: {en: 'User', ar: 'المستعمل'},
    ROLE_REPORT: {en: 'Report', ar: 'نقل'},
    chart_title: {
      en: 'How Likely are you to recommend us?',
      ar: 'ما مدى احتمالية أن توصي بنا؟',
    },
    logout: {en: 'Log out', ar: 'خروج'},
    logout_title: {en: 'Logout Successful', ar: 'نجح تسجيل الخروج'},
    logout_subtitle: {
      en: 'You have successfully logged out',
      ar: 'لقد قمت بتسجيل الخروج بنجاح',
    },
    backtologin: {en: 'Back to Login', ar: 'العودة لتسجيل الدخول'},
    adduser: {en: 'Add User', ar: 'إضافة مستخدم'},
    roles: {en: 'Roles', ar: 'الأدوار'},
    search_firstname: {en: 'Search first name', ar: 'ابحث عن الاسم الأول'},
    isactive: {en: 'Is Active?', ar: 'نشط؟'},
    all_users: {en: 'All Users', ar: 'جميع المستخدمين'},
    email: {en: 'Email', ar: 'البريد الإلكتروني'},
    first_name: {en: 'First name', ar: 'الاسم الاول'},
    last_name: {en: 'Last Name', ar: 'الكنية'},
    status: {en: 'Status', ar: 'الحالة'},
    created_on: {en: 'Create date', ar: 'تاريخ الإنشاء'},
    modified_on: {en: 'Last modified', ar: 'وزاهال'},
    active: {en: 'Active', ar: 'نشيط'},
    inactive: {en: 'Inactive', ar: 'غير عامل'},
    mark_active: {en: 'Mark Active', ar: 'مارك بالموقع'},
    mark_inactive: {en: 'Mark Inactive', ar: 'وضع علامة غير نشط'},
    add_user: {en: 'Add User', ar: 'إضافة مستخدم'},
    new_user: {en: 'New User', ar: 'مستخدم جديد'},
    personal_info: {en: 'Personal information', ar: 'معلومات شخصية'},
    change_password: {en: 'Change Password', ar: 'غير كلمة السر'},
    change_password_success: {
      en: 'Successfully changed password!',
      ar: 'تم تغيير كلمة المرور بنجاح!',
    },
    survey_respondents: {
      en: 'Survey Respondents',
      ar: 'المشاركون في الاستطلاع',
    },
    gender: {en: 'Gender', ar: 'جنس'},
    segment: {en: 'Segment', ar: 'قطعة'},
    search_maskparty: {en: 'Search mask party', ar: 'البحث عن حزب قناع'},
    send_sms: {en: 'Send SMS', ar: 'أرسل رسالة نصية قصيرة'},
    all_survey_users: {
      en: 'All Survey Respondents',
      ar: 'جميع المستجيبين في الاستطلاع',
    },
    mask_party: {en: 'Respondent ID', ar: 'مجيب'},
    branch_code: {en: 'Branch code', ar: 'رمز الفرع'},
    trans_desc: {en: 'Trans desc', ar: 'عملية الوصف'},
    served_by: {en: 'Served by', ar: 'قدم بواسطة'},
    expire_on: {en: 'Expire on', ar: 'تنتهي في'},
  }),
);
